package io.micronaut.docs;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;

record GuideProject(
    String slug,
    String displayName,
    String projectKey,
    String module,
    String repositoryName,
    String publishedGuideUrl,
    String repositoryUrl,
    String branch,
    String submodulePath,
    String platformVersionKey,
    String repositoryCreatedAt
) {
    private static final String COUNT = "project.count";
    static final String UNKNOWN_REPOSITORY_CREATED_AT = "9999-12-31T23:59:59Z";

    URI publishedGuideUri() {
        return URI.create(publishedGuideUrl);
    }

    String guideIndexPath() {
        return submodulePath + "/build/docs/guide/index.html";
    }

    String tocPath() {
        return submodulePath + "/src/main/docs/guide/toc.yml";
    }

    String generatedDocsPath() {
        return submodulePath + "/build/docs";
    }

    String platformGuideHtmlPath() {
        return submodulePath + "/build/platform-docs/guide.html";
    }

    static List<GuideProject> readManifest(Path manifestFile) throws IOException {
        if (!Files.isRegularFile(manifestFile)) {
            throw new IOException("Missing platform docs project manifest: " + manifestFile
                + ". Run ./gradlew -q scanPlatformProjects.");
        }

        Properties properties = new Properties();
        try (InputStream input = Files.newInputStream(manifestFile)) {
            properties.load(input);
        }

        int count = Integer.parseInt(properties.getProperty(COUNT, "0"));
        List<GuideProject> projects = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            String prefix = "project." + i + ".";
            String platformVersionKey = required(properties, prefix + "platformVersionKey");
            String repositoryUrl = required(properties, prefix + "repositoryUrl");
            projects.add(new GuideProject(
                required(properties, prefix + "slug"),
                required(properties, prefix + "displayName"),
                properties.getProperty(prefix + "projectKey", projectKeyFromVersionKey(platformVersionKey)),
                properties.getProperty(prefix + "module", ""),
                properties.getProperty(prefix + "repositoryName", repositoryNameFromUrl(repositoryUrl)),
                required(properties, prefix + "publishedGuideUrl"),
                repositoryUrl,
                required(properties, prefix + "branch"),
                required(properties, prefix + "submodulePath"),
                platformVersionKey,
                properties.getProperty(prefix + "repositoryCreatedAt", UNKNOWN_REPOSITORY_CREATED_AT)
            ));
        }
        return projects;
    }

    static void writeManifest(Path manifestFile, List<GuideProject> projects) throws IOException {
        Files.createDirectories(manifestFile.getParent());

        Map<String, String> values = new LinkedHashMap<>();
        values.put(COUNT, Integer.toString(projects.size()));
        for (int i = 0; i < projects.size(); i++) {
            GuideProject project = projects.get(i);
            String prefix = "project." + i + ".";
            values.put(prefix + "slug", project.slug());
            values.put(prefix + "displayName", project.displayName());
            values.put(prefix + "projectKey", project.projectKey());
            values.put(prefix + "module", project.module());
            values.put(prefix + "repositoryName", project.repositoryName());
            values.put(prefix + "publishedGuideUrl", project.publishedGuideUrl());
            values.put(prefix + "repositoryUrl", project.repositoryUrl());
            values.put(prefix + "branch", project.branch());
            values.put(prefix + "submodulePath", project.submodulePath());
            values.put(prefix + "platformVersionKey", project.platformVersionKey());
        }

        StringBuilder content = new StringBuilder("# Generated by ./gradlew -q scanPlatformProjects\n");
        for (Map.Entry<String, String> entry : values.entrySet()) {
            content.append(entry.getKey())
                .append('=')
                .append(escapeProperty(entry.getValue()))
                .append('\n');
        }
        Files.writeString(manifestFile, content.toString(), StandardCharsets.UTF_8);
    }

    static List<GuideProject> sortByRepositoryAge(List<GuideProject> projects) {
        return projects.stream()
            .sorted(Comparator.comparing(GuideProject::repositoryCreatedAt).thenComparing(GuideProject::displayName))
            .toList();
    }

    static List<GuideProject> selectBySlugs(List<GuideProject> projects, String requestedSlugs) {
        if (requestedSlugs == null || requestedSlugs.isBlank()) {
            return projects;
        }
        Map<String, GuideProject> bySlug = new LinkedHashMap<>();
        for (GuideProject project : projects) {
            bySlug.put(project.slug(), project);
        }
        List<GuideProject> selected = new ArrayList<>();
        Set<String> seen = new HashSet<>();
        for (String requestedSlug : requestedSlugs.split(",")) {
            String slug = requestedSlug.trim();
            if (slug.isBlank() || !seen.add(slug)) {
                continue;
            }
            GuideProject project = bySlug.get(slug);
            if (project == null) {
                throw new IllegalArgumentException("Unknown platform docs project slug: " + slug);
            }
            selected.add(project);
        }
        if (selected.isEmpty()) {
            throw new IllegalArgumentException("platformDocs.projectSlugs did not select any projects.");
        }
        return selected;
    }

    static List<GuideProject> shard(List<GuideProject> projects, int shardIndex, int shardCount) {
        if (shardCount < 1) {
            throw new IllegalArgumentException("Shard count must be greater than zero.");
        }
        if (shardIndex < 0 || shardIndex >= shardCount) {
            throw new IllegalArgumentException("Shard index " + shardIndex + " is outside shard count " + shardCount + ".");
        }
        List<GuideProject> selected = new ArrayList<>();
        for (int i = 0; i < projects.size(); i++) {
            if (i % shardCount == shardIndex) {
                selected.add(projects.get(i));
            }
        }
        return selected;
    }

    private static String required(Properties properties, String key) {
        String value = properties.getProperty(key);
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("Platform docs project manifest is missing " + key);
        }
        return value;
    }

    private static String projectKeyFromVersionKey(String platformVersionKey) {
        String prefix = "managed-micronaut-";
        if (platformVersionKey.startsWith(prefix)) {
            return platformVersionKey.substring(prefix.length());
        }
        return platformVersionKey;
    }

    private static String repositoryNameFromUrl(String repositoryUrl) {
        String normalized = repositoryUrl.trim();
        int slash = normalized.lastIndexOf('/');
        if (slash >= 0) {
            normalized = normalized.substring(slash + 1);
        }
        if (normalized.endsWith(".git")) {
            normalized = normalized.substring(0, normalized.length() - ".git".length());
        }
        return normalized;
    }

    private static String escapeProperty(String value) {
        return value
            .replace("\\", "\\\\")
            .replace("\n", "\\n")
            .replace("\r", "\\r");
    }
}
