package io.micronaut.docs;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Properties;

final class RepositoryMetadataCache {
    static final String DEFAULT_RELATIVE_PATH = "gradle/platform-doc-repositories.properties";

    private final Map<String, Entry> entriesByName;
    private final Map<String, Entry> entriesByProjectKey;
    private final Map<String, Entry> entriesByModule;

    private RepositoryMetadataCache(Map<String, Entry> entriesByName) {
        this.entriesByName = Map.copyOf(entriesByName);
        Map<String, Entry> projectKeyIndex = new LinkedHashMap<>();
        Map<String, Entry> moduleIndex = new LinkedHashMap<>();
        for (Entry entry : entriesByName.values()) {
            if (!entry.projectKey().isBlank()) {
                projectKeyIndex.putIfAbsent(entry.projectKey(), entry);
            }
            if (!entry.module().isBlank()) {
                moduleIndex.putIfAbsent(entry.module(), entry);
            }
        }
        this.entriesByProjectKey = Map.copyOf(projectKeyIndex);
        this.entriesByModule = Map.copyOf(moduleIndex);
    }

    static RepositoryMetadataCache read(Path metadataFile, Path projectManifest) throws IOException {
        Map<String, Entry> entries = new LinkedHashMap<>();
        if (Files.isRegularFile(metadataFile)) {
            Properties properties = new Properties();
            try (InputStream input = Files.newInputStream(metadataFile)) {
                properties.load(input);
            }
            int count = Integer.parseInt(properties.getProperty("repository.count", "0"));
            for (int i = 0; i < count; i++) {
                String prefix = "repository." + i + ".";
                put(entries, new Entry(
                    properties.getProperty(prefix + "projectKey", ""),
                    properties.getProperty(prefix + "module", ""),
                    properties.getProperty(prefix + "slug", ""),
                    properties.getProperty(prefix + "displayName", ""),
                    properties.getProperty(prefix + "name", ""),
                    properties.getProperty(prefix + "url", ""),
                    properties.getProperty(prefix + "publishedGuideUrl", ""),
                    properties.getProperty(prefix + "submodulePath", ""),
                    properties.getProperty(prefix + "createdAt", "")
                ));
            }
        }
        if (Files.isRegularFile(projectManifest)) {
            for (GuideProject project : GuideProject.readManifest(projectManifest)) {
                put(entries, Entry.from(project));
            }
        }
        return new RepositoryMetadataCache(entries);
    }

    static void write(Path metadataFile, List<GuideProject> projects) throws IOException {
        Files.createDirectories(metadataFile.getParent());
        List<Entry> entries = projects.stream()
            .map(Entry::from)
            .sorted((left, right) -> left.name().compareTo(right.name()))
            .toList();
        StringBuilder content = new StringBuilder("# Generated by ./gradlew -q scanPlatformProjects\n");
        content.append("repository.count=").append(entries.size()).append('\n');
        for (int i = 0; i < entries.size(); i++) {
            Entry entry = entries.get(i);
            String prefix = "repository." + i + ".";
            append(content, prefix + "projectKey", entry.projectKey());
            append(content, prefix + "module", entry.module());
            append(content, prefix + "slug", entry.slug());
            append(content, prefix + "displayName", entry.displayName());
            append(content, prefix + "name", entry.name());
            append(content, prefix + "url", entry.url());
            append(content, prefix + "publishedGuideUrl", entry.publishedGuideUrl());
            append(content, prefix + "submodulePath", entry.submodulePath());
            append(content, prefix + "createdAt", entry.createdAt());
        }
        Files.writeString(metadataFile, content.toString(), StandardCharsets.UTF_8);
    }

    int size() {
        return entriesByName.size();
    }

    Optional<Entry> byName(String repositoryName) {
        return Optional.ofNullable(entriesByName.get(repositoryName));
    }

    Optional<Entry> byProjectKey(String projectKey) {
        return Optional.ofNullable(entriesByProjectKey.get(projectKey));
    }

    Optional<Entry> byModule(String module) {
        return Optional.ofNullable(entriesByModule.get(module));
    }

    Map<String, String> creationDates() {
        Map<String, String> creationDates = new LinkedHashMap<>();
        for (Entry entry : entriesByName.values()) {
            if (!isUnknownCreatedAt(entry.createdAt())) {
                creationDates.put(entry.name(), entry.createdAt());
            }
        }
        return creationDates;
    }

    private static void put(Map<String, Entry> entries, Entry entry) {
        if (entry.name().isBlank()) {
            return;
        }
        entries.merge(entry.name(), entry, Entry::merge);
    }

    private static void append(StringBuilder content, String key, String value) {
        content.append(key)
            .append('=')
            .append(escapeProperty(value))
            .append('\n');
    }

    private static String escapeProperty(String value) {
        return value
            .replace("\\", "\\\\")
            .replace("\n", "\\n")
            .replace("\r", "\\r");
    }

    private static boolean isUnknownCreatedAt(String value) {
        return value.isBlank() || GuideProject.UNKNOWN_REPOSITORY_CREATED_AT.equals(value);
    }

    record Entry(
        String projectKey,
        String module,
        String slug,
        String displayName,
        String name,
        String url,
        String publishedGuideUrl,
        String submodulePath,
        String createdAt
    ) {
        static Entry fromName(String repositoryName) {
            return new Entry(
                "",
                "",
                "",
                "",
                repositoryName,
                "",
                "",
                "",
                GuideProject.UNKNOWN_REPOSITORY_CREATED_AT
            );
        }

        private static Entry from(GuideProject project) {
            return new Entry(
                project.projectKey(),
                project.module(),
                project.slug(),
                project.displayName(),
                project.repositoryName(),
                project.repositoryUrl(),
                project.publishedGuideUrl(),
                project.submodulePath(),
                project.repositoryCreatedAt()
            );
        }

        private Entry merge(Entry fallback) {
            return new Entry(
                choose(projectKey, fallback.projectKey),
                choose(module, fallback.module),
                choose(slug, fallback.slug),
                choose(displayName, fallback.displayName),
                choose(name, fallback.name),
                choose(url, fallback.url),
                choose(publishedGuideUrl, fallback.publishedGuideUrl),
                choose(submodulePath, fallback.submodulePath),
                isUnknownCreatedAt(createdAt) ? fallback.createdAt : createdAt
            );
        }

        private static String choose(String value, String fallback) {
            return value == null || value.isBlank() ? fallback : value;
        }
    }
}
